/*
 * This is sample code generated by rpcgen.
 * These are only templates, and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <unistd.h>
#include <time.h>

#define MAX_REQUESTS 10000

char decode_op(int int_op)
{
    switch (int_op)
    {
        case 0:
            return '+';
        case 1:
            return '-';
        case 2:
            return '*';

        case 3:
            return '/';
    }

    return '?';
}

void
service_prog_1(char *host)
{
    CLIENT *clnt;
    double *result;
    struct REQUEST service_proc_1_arg;
    int *num;
    void *number_proc_1_arg;

#ifndef    DEBUG
    clnt = clnt_create(host, SERVICE_PROG, SERVICE_VER, "udp");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif    /* DEBUG */
    struct timeval info;
    clnt_control(clnt, CLGET_TIMEOUT, (char *) &info);
    printf("timeout = sec: %ld, usec: %ld\n", info.tv_sec, info.tv_usec);

    int request = 1;

    do
    {
        service_proc_1_arg.arg1 = rand() % 1000 / 10.0;
        service_proc_1_arg.arg2 = rand() % 1000 / 10.0;
        service_proc_1_arg.op = rand() % 4;

        num = number_proc_1(&number_proc_1_arg, clnt);
        if (num == (int *) NULL)
        {
            clnt_perror(clnt, "call failed");
            exit(1);
        }

        service_proc_1_arg.number = *num;

        result = service_proc_1(&service_proc_1_arg, clnt);
        if (result == (double *) NULL)
        {
            clnt_perror(clnt, "call failed");
            exit(1);
        }

        printf(
            "%d %f %c %f = %lf\n",
            service_proc_1_arg.number,
            service_proc_1_arg.arg1,
            decode_op(service_proc_1_arg.op),
            service_proc_1_arg.arg2,
            *result
        );

        request++;
    }
    while (request <= MAX_REQUESTS);
#ifndef    DEBUG
    clnt_destroy(clnt);
#endif     /* DEBUG */
}

int
main(int argc, char *argv[])
{
    char *host;

    srand(time(NULL));

    if (argc < 2)
    {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    service_prog_1(host);
    exit(0);
}
