/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct REQUEST {
	int number;
	int op;
	double arg1;
	double arg2;
};
typedef struct REQUEST REQUEST;

#define SERVICE_PROG 0x20000001
#define SERVICE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SERVICE_PROC 1
extern  double * service_proc_1(struct REQUEST *, CLIENT *);
extern  double * service_proc_1_svc(struct REQUEST *, struct svc_req *);
#define NUMBER_PROC 2
extern  int * number_proc_1(void *, CLIENT *);
extern  int * number_proc_1_svc(void *, struct svc_req *);
extern int service_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SERVICE_PROC 1
extern  double * service_proc_1();
extern  double * service_proc_1_svc();
#define NUMBER_PROC 2
extern  int * number_proc_1();
extern  int * number_proc_1_svc();
extern int service_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_REQUEST (XDR *, REQUEST*);

#else /* K&R C */
extern bool_t xdr_REQUEST ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
