/*
 * This is sample code generated by rpcgen.
 * These are only templates, and you can use them
 * as a guideline for developing your own functions.
 */

#define MAX_CLIENT_COUNT 2048

#include "bakery.h"
#include <unistd.h>
#include <math.h>
#include <stdbool.h>

static bool choosing[MAX_CLIENT_COUNT] = {false};
static int numbers[MAX_CLIENT_COUNT] = {0};
static int max_index = 0;

double process(struct REQUEST *request)
{
    sleep(rand() % 4 + 1);

    switch (request->op)
    {
        case ADD:
            return request->arg1 + request->arg2;
        case SUB:
            return request->arg1 - request->arg2;
        case MUL:
            return request->arg1 * request->arg2;
        case DIV:
            if (!request->arg2) {
                return NAN;
            }
            return request->arg1 / request->arg2;
    }

    return NAN;
}

double *
service_proc_1_svc(struct REQUEST *argp, struct svc_req *rqstp)
{
    static double result;

    for (int i = 1; i < MAX_CLIENT_COUNT; i++) {
        while (numbers[i] != 0 && numbers[i] < argp->number) {}
    }

    result = process(argp);

    int index = -1;
    for (int i = 0; i < MAX_CLIENT_COUNT; i++)
    {
        if (numbers[i] == argp->number)
        {
            index = i;
            break;
        }
    }

    numbers[index] = 0;

    return &result;
}

int *
number_proc_1_svc(void *argp, struct svc_req *rqstp)
{
    static int number;

    choosing[max_index] = true;

    int max = numbers[0];
    for (int i = 1; i < MAX_CLIENT_COUNT; i++)
        if (numbers[i] > max)
            max = numbers[i];

    number = max;
    numbers[max_index] = ++number;
    choosing[max_index] = false;
    max_index++;

    return &number;
}
